#100 qiita eigenvalueのプルリクエスト
furukawa-laboratory/workout_report_2019 pull request #108
Opened 2019-07-01 11:14 UTC by takanoshuhei

## 取り組んだトレーニングの概要
>固有値、固有ベクトルの概要を説明したうえで、どのような場面で便利なのかを二次形式と微分方程式>の例から体感することで固有値、固有ベクトルに対する理解を深める。
>「ゼロから学ぶ線形代数」という本に詳しく乗っているのでそれを理解し、参考にしながら執筆する。

記事を書いている内に客観的な視点での内容の精査が難しくなってきたので、記事の内容に関した相談の意味も兼ねたプルリクです。

close #100 　

## 記事の目的
固有値、固有ベクトルが実際にどのように便利かを応用例を実装することで体感する。
## Action list
- 数学的な応用例として二次形式を実装した
- 機械学習への応用例としてPCAをスクラッチ実装した

## レビュワーへの質問
書いている途中で理論にどこまで言及するべきなのか線引きがわからなくなりました。
特に以下の点についてコメントして頂きたいです。
- 固有値、固有ベクトルに対して、固有ベクトルは線形変換後も向きが変わらないベクトル、固有値はその倍率といった事実だけを述べているのですが、「行列の本質を表している」等といった直感的な説明などもした方が良いのでしょうか？

- 二次形式は数式の証明が多めで、主成分分析は数式が少なめの構成になっています。どの程度の塩梅がちょうどよいのでしょうか？(数式を書きすぎるとくどい気がしてきました)

- その他何か足りない点、分かりづらい説明、変な言葉遣いなどがあれば教えていただきたいです。

2019-07-05 13:31 UTC, TetraMiyazaki requested changes
> 共分散行列の大きな固有値に対応した固有ベクトルを主成分とすることは、そのデータの分散の大きい軸を選びなおすことになります。

ここのコメントの分だけひっかかりました。
それ以外は訂正レベルで大丈夫です。

2019-07-06 10:51 UTC, takanoshuhei commented
> > 共分散行列の大きな固有値に対応した固有ベクトルを主成分とすることは、そのデータの分散の大きい軸を選びなおすことになります。
> 
> ここのコメントの分だけひっかかりました。
> それ以外は訂正レベルで大丈夫です。

コメントありがとうございます。確かにそこはふわっとした理解で書いていた部分ですので、より深い理解をもってもう一度書き直したいと思います。書き直したらまた再度コメントします。

2019-07-06 11:12 UTC, kpasso1015 commented
> 高野くん
HackMD上のコメントのところで返信してくれたら十分ですよ(どちらでもいい)

2019-07-07 07:26 UTC, ae14watanabe reviewed
具体的な指摘はHackMDの方にコメントしているのでこちらでは総評（？）を。

余裕で及第点はクリアしていると思います。ナイスファイトです！大変だったでしょう。
あくまでより良くするためのアドバイスです。
「二次形式」「主成分分析」と2つ例を挙げていますが、何を伝えたいか、読み手にどう思って欲しいか明確にしてみてください。「固有値って便利だなぁ」なのか「固有値って本質的なんだなぁ」なのか。それを伝えるためにどういう流れを組み立てればいいか、再考するといいかと思います。

他にも記事はあると思うので使える時間考えつつも、この辺りを頑張るとさらに良い記事になりそうです。引き続きファイトだ！

2019-07-07 07:27 UTC, ae14watanabe commented
修正してまたコメントが欲しい時は`Re-request review`を押してね
![image](https://user-images.githubusercontent.com/19607449/60765332-15288a00-a0d4-11e9-88f1-192209dec383.png)

2019-07-07 08:25 UTC, yoneda88 reviewed
同じく詳細はHackMDのコメントに書いているので、そっち見てね。

大まかには以下の2点
１．内積の公式を乗せてるけど、これ正しい？
２．「二次形式への応用」「固有値問題」において、
　　　①まず「何が知りたいか or したいか？」を伝える
　　　②次に「けどそのまま見ても分からない or できない」ってことを読者に訴え
　　　③最後に「でも固有値を使えば分かる or できる」ってことを通して固有値スゲーって共感させる
　　って下りで書いてあげると、固有値がどう役立つか読者に伝わると思います！

例）「二次形式への応用」
　　もしも「二次形式の標準化からの二次曲線の種類を固有値を見ることで知ろう」的な話であれば、
　　　①𝑎𝑥2+2𝑏𝑥𝑦+𝑐𝑦2=0って関数はa, b, c, dの値によって、色々な形をとるよ！
　　　②a, b, c, dを見ただけじゃ形が分からない！でも知りたい！
　　　③abcd行列の固有値を見れば、形がわかる！？

2019-07-20 04:44 UTC, yoneda88 reviewed
修正or返事待ち

2019-07-20 04:53 UTC, takanoshuhei commented
> 修正or返事待ち

長い間返事が出来ずすみません。もう少し時間がかかりそうです。なるべく早く修正したいと思います。

2019-07-22 09:52 UTC, senoura reviewed
お疲れ様です。
気になったとこコメント入れました。

2019-07-22 12:47 UTC, takanoshuhei commented
主成分分析の説明についてとすぐに直せる部分について修正しました。
二次形式を用いた関数の形の判別についてはまだ調べられてないので、今は関数が取る値がわかる、といった説明の仕方に直しています。いずれ関数の形についても言及したいと思っています。

2019-07-22 13:59 UTC, yoneda88 approved these changes
OKKKKKKKKK

2019-07-23 07:42 UTC, takuro-Ishida commented
石田が気になったところだけコメントしました.

固有値の定義と固有値・固有ベクトルがどのようなところで応用されているのかが石田はよくわかりました！素敵でした！
あとはそれぞれの内容の修正を頑張ってください.(他の方が言ってたコメントを修正したら石田は問題ないかと思うので、コメントの内容を全て修正したら石田はApproveします)

2019-07-23 09:21 UTC, senoura approved these changes
コメントの修正を確認しました！
お疲れ様です。approveします。

2019-07-23 09:24 UTC, ae14watanabe reviewed
昨日、口頭では言いましたが、かなりボリューミーなので
- 固有値とはなんぞや
- 二次形式の例
- 主成分分析の例
の3つの記事に分けてはどうでしょう。「固有値シリーズ（全三部作）」とかやっとけばいいと思います。
やっぱりQiitaの記事ってほどほどの長さでないとかなり読みにくいので、そちらの方がオススメです。

2019-07-23 09:30 UTC, takanoshuhei commented
> 昨日、口頭では言いましたが、かなりボリューミーなので
> 
> * 固有値とはなんぞや
> * 二次形式の例
> * 主成分分析の例
>   の3つの記事に分けてはどうでしょう。「固有値シリーズ（全三部作）」とかやっとけばいいと思います。
>   やっぱりQiitaの記事ってほどほどの長さでないとかなり読みにくいので、そちらの方がオススメです。

3本に分ける際には現在の文から大幅に変えずに3本にわけたほうがいいですか？
それとも各々をさらに深く掘り下げていく形になるのでしょうか？

2019-07-23 09:33 UTC, ae14watanabe commented
> 3本に分ける際には現在の文から大幅に変えずに3本にわけたほうがいいですか？
それとも各々をさらに深く掘り下げていく形になるのでしょうか？

いや、中身自体はそこまで大きく変える必要ないと思います。1つ1つがかなり詳しくやってるので。
各記事の冒頭はうまく繋がるようにいい感じにしないといけないですが、その辺は高野君ならうまいことできると思うのでやってみてください。

2019-07-23 09:51 UTC, takanoshuhei commented
> > 3本に分ける際には現在の文から大幅に変えずに3本にわけたほうがいいですか？
> > それとも各々をさらに深く掘り下げていく形になるのでしょうか？
> 
> いや、中身自体はそこまで大きく変える必要ないと思います。1つ1つがかなり詳しくやってるので。
> 各記事の冒頭はうまく繋がるようにいい感じにしないといけないですが、その辺は高野君ならうまいことできると思うのでやってみてください。

わかりました！分ける方向で考えていきます！分けたらまたプルリク出します。

2019-07-24 05:51 UTC, takanoshuhei commented
これまで記述していたHackmdの各章(固有値ってなんだ！？、二次形式、主成分分析)を3本に切り分けるため、各章に「はじめに」と「まとめ」を追記しました。流れが不自然でなければ各章を切り分けて投稿したいと思います。

2019-07-24 11:23 UTC, Kusumoto-Keisuke reviewed
お疲れ様です．式（3）のあたりにコメントしました．

2019-07-25 13:42 UTC, takanoshuhei commented
> お疲れ様です．式（3）のあたりにコメントしました．

修正しました！確認よろしくお願いいたします！

2019-07-25 16:13 UTC, TetraMiyazaki approved these changes
リクエストしたとこがちゃんと変わっていたのでApproveします。
３本分の記事() お疲れ様です。

2019-07-25 18:12 UTC, Kusumoto-Keisuke approved these changes
修正箇所の確認できたのでApproveします！

2019-07-26 00:47 UTC, ae14watanabe approved these changes
お疲れ様でーす、HackMDにコメントもしましたが以下の2点ぐらいです

- ベクトルのフォント$\mathbf{e}_1$とかの方が俺は好き
- 各記事に、他の記事への誘導を入れといてね

ということでこの辺を修正したらもういいと思うのでApproveします

2019-07-26 05:01 UTC, takuro-Ishida approved these changes
他のコメントを修正していただけるということで先にApproveしておきます

2019-07-27 09:00 UTC, takanoshuhei commented
> お疲れ様でーす、HackMDにコメントもしましたが以下の2点ぐらいです
> 
> * ベクトルのフォント$\mathbf{e}_1$とかの方が俺は好き
> * 各記事に、他の記事への誘導を入れといてね
> 
> ということでこの辺を修正したらもういいと思うのでApproveします

ベクトルの書式の修正を終えました！他記事へのリンクも、記事が揃い次第追記したいと思います

2019-07-29 07:36 UTC, merged