#107_[Qiita1本目] SVMの基礎部分について
furukawa-laboratory/workout_report_2019 pull request #112
Opened 2019-07-10 15:28 UTC by oirom

## 取り組んだトレーニングの概要
> 授業やワークアウトで学んだ知識内容を整理し，Qiitaに投稿する記事としてまとめる．１本目では教師付き学習によるパターン認識モデルとして有名なSVMについて記事を書く．

>獲得を目指すスキル
> SVMにおけるマージンについて説明できる．
> SVMにおけるマージン最大化の原理について説明できる．

Qiita記事一本目のプルリクエストです．7/10までに第一稿を提出としてたためプルリクエストを出しました．が，完成にはまだ少しかかりそうです．記事の流れを確認していただきたくプルリクエストを出しました．

HackMDのリンク：https://hackmd.io/@p9rI7JgpQ5iM3kmdfOjSjA/HJq00rhxH

close #107 

## 記事の目的
パターン識別器の一手法であるSVMについて，その基本的な原理を式を追って理解するとともに，図を交えた自分なりの説明を加えて読者に伝わるSVMの説明を目指す．記事ではイメージしやすい2クラスのパターン識別器を中心に話を進める．

## 進捗状況
- SVMのマージン最大化の原理について書いた
- SVMの制約条件について書いた

## 今後の予定
下記の項目を加筆し，7/14までに再度プルリクエストを出す．
- SVMの目的関数について書く
- SVMの制約条件を考慮したうえでの目的関数の開放について書く
- まとめる

## 感想
issue提出当初の目的だったマージンとマージン最大化について理解する点はクリアできた．
しかし，それだけだと記事にボリュームがないことに加え，ワークアウトで学んだことを発揮するには不十分であった．なので，SVMにおける目的関数の最初化をラグランジュの未定乗数法を導入することで解く方法について記述する．可能であれば，SVMにおける最適化問題が2次計画問題として知られていることや，双対問題に帰着して解かれることについても言及する．

## レビュワーへの質問
説明の順序に自信がないため，記事の流れに違和感がないかチェックしていただきたいです．
例）「マージン最大化の原理を説明したあとに目的関数や制約条件の話するのはおかしいよ」など

2019-07-11 07:13 UTC, takuro-Ishida commented
お疲れ様です！

> レビューワーへの質問

石田的には全体の流れとしてはSVMの学習の話をマージン最大化と2クラス分類におけるSVMの制約条件の間に入れた方がいいと思いました.

理由としては
与えられているもの→SVMのアイデア(どうやって線形分類したいのか)→SVMのアイデアを数式にどう落としているのか(目的関数の導出まで)→それをどう解くのか
という順番がわかりやすいと思ったからです。

具体的には
### SVMによる2クラス分類
* 与えられているもの
* マージン最大化
* SVMの学習
* 2クラス分類におけるSVMの制約条件
* SVMの目的関数
というような流れの方がいいかと思います.
その他は全然いいと思います！

## 記事の内容で気になったところ
記事の中で気になった点を上げていきます.
* SVMのタスクを「パターン認識」と言っているところ。
パターン認識ではなく、分類と言った方がよいかと思います.
軽く調べてみるとパターン認識というのは、機械学習の様々まタスク(回帰、分類、次元削減、クラスタリングetc.)の総称なので、勘違いされる可能性があるかなーと.山内くんは分類の話をしたいと思うので。
* SVMの学習の図
演算素子(x_iにw_iという重みをつける部分)がない。

## 個人的に
個人的には、図のところが非常にわかりやすくて好きです！
個人的には、最後にカーネル法を使って非線形分類もできるよ！ってところも触れてくれると嬉しいです！
すごく素敵な内容になっているので頑張ってください！

2019-07-12 07:07 UTC, TetraMiyazaki requested changes
大作お疲れ様です。

コメントでも書きましたが、こちらでも言及します。

# 出だしの部分

>パターン認識のタスクは，未知の認識対象を観測し，得られた特徴量からその対象がどのクラスに属するかを判定する識別器を構成することです．

未知の認識対象を識別する話と、識別機を構築する話がごっちゃになっている気がします。パターン認識?(分類?)を知っている人にとってはわかる話かもしれませんが、初見の人にとってはわかりづらい一文だなと思ってしまいました。
どっかにあった文章なら知りたいです。

具体的には

未知の認識対象を識別します。そのために、識別機を構築する。
という流れで、"やりたいこと"と"問題設定"を区別して書いて欲しいと思いました。

# Approveについて

他は石田さんと同じです。
自分が反応したところに何かしらリアクションを返してくれたらApproveします。

2019-07-12 10:29 UTC, oirom commented
@takuro-Ishida ご指摘ありがとうございます！
> SVMのタスクを「パターン認識」と言っているところ。
パターン認識ではなく、分類と言った方がよいかと思います.
軽く調べてみるとパターン認識というのは、機械学習の様々まタスク(回帰、分類、次元削減、クラスタリングetc.)の総称なので、勘違いされる可能性があるかなーと.山内くんは分類の話をしたいと思うので。

確かに自分が話をしたいのは分類の話なので内容を訂正します！

> SVMの学習の図
演算素子(x_iにw_iという重みをつける部分)がない。
訂正します！

カーネルを使った非線形分類は別記事にしようか考えているところです（汗
余力があれば同一記事に含めたいと思います！

2019-07-12 11:29 UTC, oirom commented
@kpasso1015 ご指摘ありがとうございます！

> パターン認識のタスクは，未知の認識対象を観測し，得られた特徴量からその対象がどのクラスに属するかを判定する識別器を構成することです．

上記の文言ですが，[こちら](https://home.hiroshima-u.ac.jp/tkurita/lecture/svm.pdf)の「2.1 パターン認識における学習」を参考にしています．

ご指摘を受けて自分なりに考えました，認識に間違いがあったようです．

- 「パターン認識のタスクは」は，対象とするデータの特徴を認識し，その特徴とクラスを対応付けること．
- 識別器の構築は，「パターン認識のタスク（パターン認識に与えられたタスク）」ではなく，パターン認識を実現するうえで必要不可欠なタスク．パターン認識を実現するうえで達成すべきタスク，つまりは「パターン認識におけるタスク」であると理解しました．

文章が分かりづらいかもしれません，すみません．
上記の認識で間違いないでしょうか？

2019-07-12 13:42 UTC, kpasso1015 commented
@oirom 
> 上記の文言ですが，こちらの「2.1 パターン認識における学習」を参考にしています．

確認して色々他の文献を探りましたが、自分も不確かなところがあったようです。
パターン認識はタスクというより分野として捉えている分野の総称として述べている文が多く見られました。
そもそもが抽象的な概念であり他の文献も探したところ、Exactな回答を述べたものは少なかったです。あんまり本質的じゃなかったかもしれません。すみません。

> 「パターン認識のタスクは」は，対象とするデータの特徴を認識し，その特徴とクラスを対応付けること．

自分はそういう認識でした。

>> パターン認識とは観測されたパターンを **あらかじめ定められた** 複数の概念のうちの一つに対応させる処理である。(石井健一郎「わかりやすいパターン認識」p1より)

ここに **あらかじめ** とある通り、上の文では、クラスが**いつ**定義されたのかわからなかったのが自分はひっかかったみたいでした。

> 上記の認識で間違いないでしょうか？

大丈夫です。

ありがとうございました。引き続き頑張ってください。

2019-07-12 13:42 UTC, TetraMiyazaki approved these changes

2019-07-14 12:20 UTC, takuro-Ishida commented
@oirom 
カーネル法の話は、@oriumの視野の中に入っているかどうかが自分の中では重要だったので
同じ記事でも別でも問題ないかと思います.

2019-07-18 09:04 UTC, senoura reviewed
「SVMによる２クラス分類」の章の「基本の部分」って部分がいまいちわかりませんでした。
分離直線もわからずにその上にデータが乗っているというのは判断できないから分離直線はわかっている前提なのかなって思っていたんですが、そこからｈを求めるって話になって、あれ？ってなってしまいました。
ここの基本の部分はどんな話をしているんでしょうか？

2019-07-18 11:18 UTC, ae14watanabe requested changes
> 記事の流れを確認していただきたく

まぁ大まかには良いんじゃないかなー、sectionとかsubsectionの階層構造はもうちょっと見直す必要があるけど

細かい修正はコメントに書いているのでそちらを参照してください。
最終的なwとhの式がバチっと書いてないのがかなり気になりました。

2019-07-21 23:55 UTC, oirom commented
@ae14watanabe コメントありがとうございます．
>まぁ大まかには良いんじゃないかなー、sectionとかsubsectionの階層構造はもうちょっと見直す必要があるけど
>細かい修正はコメントに書いているのでそちらを参照してください。
最終的なwとhの式がバチっと書いてないのがかなり気になりました。

指摘を受けまして記述が途中までだった解法を追記しております．
wとhの式をばちっと書いていますのでご確認よろしくお願いいたします！

2019-07-22 00:04 UTC, oirom commented
@senoura コメントありがとうございます．
>「SVMによる２クラス分類」の章の「基本の部分」って部分がいまいちわかりませんでした。
分離直線もわからずにその上にデータが乗っているというのは判断できないから分離直線はわかっている前提なのかなって思っていたんですが、そこからｈを求めるって話になって、あれ？ってなってしまいました。
ここの基本の部分はどんな話をしているんでしょうか？

この部分では，以下の項目についてわかりやすく図を用いて説明するつもりでした．
 - 分離直線の式 (f(x)=wx+h)が代表的な直線の公式(y=ax+b)とは異なるのか
 - 直線の上にあるサンプルと下にあるサンプルで符号が異なること
 - 分離直線の式 (f(x)=wx+h)におけるhが何を表すのか
 - 分離直線に乗るサンプルを識別器にかけた際に出力が0になること

しかし，書いているうちにその他の内容と重複する点や文脈を考慮し，現在記事に含めるか迷っている次第です．

2019-07-22 13:45 UTC, ae14watanabe commented
`SVMについて2クラス分類を中心に` はタイトルだよね、Qiitaだとタイトルつけられるんだけど、HackMDの場合はタイトル＝一番最初の`# タイトル` になってしまうので気をつけて 
そのあとの`パターン認識とは` が `##` になってるのがちょっと違和感ありますね
![image](https://user-images.githubusercontent.com/19607449/61637154-fc25f880-acd1-11e9-894a-c87f5e63a5ab.png)

構成というか、こういう階層構造というのはかなり大事で、結局自分の伝えたいことを構造化できているというのは、理解度を測る意味でも、人にわかりやすく伝える意味でも重要なので意識してみてください。

2019-07-22 13:47 UTC, ae14watanabe approved these changes
しっかり式の正誤を見てるわけではないですが、最後にwとhの推定値出してくれているのでApproveします。結局のところ、アルゴリズム的にはlambdaの最適化をすることになるのかな？

2019-07-22 15:24 UTC, ae14watanabe commented
@yoneda88 さんと話していたのですが
「線形分離可能であることを仮定します」というくだりがありますよね。
今回の記事では、ソフトマージンに関する言及がないので「SVMは線形分離可能なデータしか扱えない」というミスリーディングが起こるのではないか、と思いました。

ハードマージンSVMの説明って、ソフトマージンSVMまで理解するためのステップだと思います。なので、「ハードマージンSVMの説明はそういう立ち位置なのだ」ということが分かるような構成にしてくれるとより分かりやすくなると思います。

例えばなんですが、記事の冒頭に以下のようなSVMの全体像が掴めるような図を入れてみてはどうでしょう？
![IMG_5633](https://user-images.githubusercontent.com/19607449/61644648-0a7b1100-ace0-11e9-90c2-e87e2b397890.JPG)
（説明文はわりとてきとーですが、ええ感じにしてみてん）
上から下にかけてどんどんパワーアップさせていったもの、みたいなニュアンスが入るとより良さそうですね

これを提示した上で、
- 一般的にSVMを使うときはカーネルSVMが用いられる（一番generalな表現になってるしね）
- SVMをちゃんと理解しようと思ったら、まずはハードマージンSVMの導出を追う必要がある
- この記事ではハードSVMをやります

ということを説明するとかなり分かりやすい記事になるんじゃないかな
ハードマージンSVMそのものの説明は、現状の説明でいいと思います。

2019-07-22 20:44 UTC, yoneda88 reviewed
お疲れ様です。hackMDにコメントを追加しました。ご確認をよろ
あと、SVMの目的関数やKKTあたりはあんまり式が追えていませんので、コメントできてません！

そこのあたりのチェックやコメントが欲しい場合は言ってください！投稿後になるかもだけど、式を追ってコメントしますので

2019-07-23 05:56 UTC, senoura approved these changes
基本の部分で言いたかったこと伝わりました。
今の構成(7/23時点)で良いと思います。
approveします。

2019-07-24 04:44 UTC, oirom commented
> しっかり式の正誤を見てるわけではないですが、最後にwとhの推定値出してくれているのでApproveします。結局のところ、アルゴリズム的にはlambdaの最適化をすることになるのかな？

アルゴリズム的にはλの最適化です．
記述がありませんでしたので追記します．m(_ _)m

2019-07-24 04:55 UTC, oirom commented
> お疲れ様です。hackMDにコメントを追加しました。ご確認をよろ
> あと、SVMの目的関数やKKTあたりはあんまり式が追えていませんので、コメントできてません！
> 
> そこのあたりのチェックやコメントが欲しい場合は言ってください！投稿後になるかもだけど、式を追ってコメントしますので

2019-07-24 07:53 UTC, oirom commented
@ae14watanabe 
章については`#`を使うように変更いたしました．

また，線形分離可能を仮定する過程や，ハードマージンSVMの立ち位置，そのほかの手法の簡単な紹介を行い，読者のミスリーディングを減らすよう見直しました．

ご確認お願いいたします．

2019-07-25 06:09 UTC, yoneda88 approved these changes
ＯＫです！

2019-07-25 08:55 UTC, Kusumoto-Keisuke approved these changes
お疲れ様です．
分かり易くかかれていて，私も勉強になりました．
内容的には問題ないと思うのでApproveします．

タイポレベルですが，Hack MD にコメント残しました．
余裕があれば修正してください．

2019-07-26 00:07 UTC, ae14watanabe reviewed
@oirom チェックしました！分かりやすくなったと思います！一点だけ気になったので、コメントもしたのですがここにも乗っけますね

カーネルトリックSVMって、高次元空間で線形分離可能なことを仮定してるんでしょうか？高次元空間でもソフトマージン的にちょっと許すよ的なことはやってない？
ソフトマージンSVMの内積をカーネルに置き換えただけだったら、高次元空間中でソフトマージンSVMを適用している感じになるんじゃないかなぁと思いました。

2019-07-26 02:26 UTC, oirom commented
>カーネルトリックSVMって、高次元空間で線形分離可能なことを仮定してるんでしょうか？高次元空間でもソフトマージン的にちょっと許すよ的なことはやってない？
ソフトマージンSVMの内積をカーネルに置き換えただけだったら、高次元空間中でソフトマージンSVMを適用している感じになるんじゃないかなぁと思いました。

PRMLでもカーネルSVMを説明したのちに，カーネルSVMに対してソフトマージンを導入しています．つまり，カーネルSVMでもソフトマージンは使えて，線形分離を仮定する必要はないです．
自分の説明だと間違いでした...。
訂正いたします

2019-07-26 07:12 UTC, oirom commented
@takuro-Ishida コメント部分を修正いたしました．ご確認おねがいします．

2019-07-26 07:23 UTC, ae14watanabe approved these changes
カーネルSVMの説明の細かい言い回しについて、HackMD上でコメントしました。
好みの部分がもしかしたら大きいかもしれませんが、納得してくれたらそちらに修正してもらうといいかな。
それ以外はokなので、Approveします。

2019-07-26 08:07 UTC, takuro-Ishida approved these changes
お疲れ様です.
ちょっと式の部分は追えてないので、式の厳密さはちょっとコメントできていないのですが、全体として問題ないと思うのでApproveします.

Qiitaにあげる前でもいいので、コメントやタイポに気をつけていただけたらいいと思います.

2019-07-27 08:23 UTC, merged