[Qiita2本目] "線形分離可能" と分類
furukawa-laboratory/workout_report_2019 pull request #121
Opened 2019-07-16 09:44 UTC by forusufia

## 取り組んだトレーニングの概要
パラメトリック＆ノンパラメトリック勉強会でScrapboxにまとめた線形分離について、分類問題の感覚に触れるのに良いと考え、プログラムの実装などいくつかの追加・修正を行って記事にまとめました。

HackMD: https://hackmd.io/eD7SHxNhQ-GR5oLA-JYEvg

close #114

AND回路出力の分類

![2](https://user-images.githubusercontent.com/38308647/61283782-a1376180-a7f8-11e9-9c4b-c973f2ef2496.PNG)

## 獲得を目指したスキル
- 記事を見た人が線形分離可能と分類の感覚を掴んでくれる説明

## Action list
- [x] 線形分離可能のと分類の説明
- [x] 線形SVMプログラム実装

## レビュワーへの質問

## 感想
記事を作りながら分類のことを考えていたが、まだまだ腑におちていない部分があったと改めて認識したので調べていくことにする。

2019-07-21 08:56 UTC, ae14watanabe requested changes
ご苦労様です。「線形分離可能」と学習の話は分けたほうがいいのではないでしょうか？というかどちらについても話したいのであれば、それぞれに対応するsectionがないとおかしい気がします。何を伝えたいのかをワンセンテンスぐらいで書いてみてもいいかもしれないですね。そこから構成を見直して1つの読み物として成立するように再構成してみてください。

2019-07-22 12:24 UTC, yoneda88 reviewed
お疲れ様です。コメントはhackmd。確認よろ。

2019-07-23 06:37 UTC, senoura reviewed
お疲れ様です！
コメントをつけました。
線形分離ってのがなんなのかを例を示しながら説明するっていう記事なんでしょうか？

2019-07-29 12:21 UTC, TetraMiyazaki reviewed
お疲れ様です。
2本目にも書きましたが、どんなスキルセットを得たかったのか。書いてもらえれば自分はApproveします。

2019-07-29 13:29 UTC, Kusumoto-Keisuke reviewed
2つ目の記事同様これから修正すると思うので Comment にしておきます．変更前に，どういった変更をしたいのかをコメントとして残しておくのがおすすめですよ．

2019-07-30 07:14 UTC, forusufia commented
２本目と３本目を入れ替える考えもありましたが、３本目のほうの修正が難航し、こちらの修正が先に進みました。話が２転してしまい申し訳ありませんが、校正のほうよろしくお願いいたします。

2019-07-30 07:16 UTC, forusufia commented
> ご苦労様です。「線形分離可能」と学習の話は分けたほうがいいのではないでしょうか？というかどちらについても話したいのであれば、それぞれに対応するsectionがないとおかしい気がします。何を伝えたいのかをワンセンテンスぐらいで書いてみてもいいかもしれないですね。そこから構成を見直して1つの読み物として成立するように再構成してみてください。

何をしたかったかもう一度考えてみて、タイトルから再構成しました。

2019-07-30 07:17 UTC, forusufia commented
> お疲れ様です！
> コメントをつけました。
> 線形分離ってのがなんなのかを例を示しながら説明するっていう記事なんでしょうか？

はい、線形分離について説明して、イメージを掴んでもらえたらという記事です

2019-07-30 07:23 UTC, forusufia commented
> お疲れ様です。
> 2本目にも書きましたが、どんなスキルセットを得たかったのか。書いてもらえれば自分はApproveします。

自分なりのイメージを作って/見つけて理解する、というスキルを今回は線形分離について記事で説明することで試しています。

2019-07-30 07:24 UTC, forusufia commented
> 2つ目の記事同様これから修正すると思うので Comment にしておきます．変更前に，どういった変更をしたいのかをコメントとして残しておくのがおすすめですよ．

いつも変更後に返信してしまっていました。このコメントも修正後です・・・。アドバイスありがとうございます。考えを整理する意味でもコメントを残すようにしていきたいと思います。

2019-07-30 07:58 UTC, ae14watanabe approved these changes
お疲れ様でーす。もうちょっとこんな風に書いてくれんかなーとか出てきたんですが、自分の好みの話になってきた気がするのでApproveします。ちょいちょいコメントも追加してますが、なんかイチャモンじゃないのこれ、という気が自分でしてきたのでApproveで問題ないと思います。

ところで、線形分離でググってたら面白そうなページあったのでshareしときますね。
- パーセプトロンの解の存在条件（線形分離可能かどうかの判定ができるかも）
http://cai.cs.shinshu-u.ac.jp/Lecture/Neuro3/node6.html
- あらゆるデータを線形分離可能にしてしまう変換の話
http://conditional.github.io/blog/2013/07/10/vanishing-component-analysis/

2019-07-30 08:53 UTC, ae14watanabe commented
> 自分なりのイメージを作って/見つけて理解する、というスキルを今回は線形分離について記事で説明することで試しています。

Workoutのメニューにはそういうスキルないと思うんだけど、私が「3本のうち1本ぐらいは設定されてるスキルセットに即したやつ書いたら」って言ってたのは覚えてるかな。次の記事でやる感じかな。

2019-07-30 10:32 UTC, senoura reviewed
お疲れ様です！
コメント入れました～

2019-07-31 03:18 UTC, yoneda88 approved these changes
OKです。
加筆必須ではないですが、
「イメージを掴む」の意味が分からなかったので、原田くんが
　「線形分離可能の何が分からなかったのか」そして「どう理解しようとしたか」
を書くといいとおもいました（KONAMI感

2019-07-31 03:35 UTC, forusufia commented
> > 自分なりのイメージを作って/見つけて理解する、というスキルを今回は線形分離について記事で説明することで試しています。
> 
> Workoutのメニューにはそういうスキルないと思うんだけど、私が「3本のうち1本ぐらいは設定されてるスキルセットに即したやつ書いたら」って言ってたのは覚えてるかな。次の記事でやる感じ？

はい、次の記事で前処理についてやります

2019-07-31 04:20 UTC, ae14watanabe commented
米田さんと話していたのですが、結局「はじめに」の部分の話なんですけど、「自分の学習用メモ」なのか「イメージを捉えることは大事！」なのか「解説」なのかスタンスがイマイチ見えないかなと。そこが見えないとコメントもしづらいです。

ただ、まぁここにあんまり時間かけてもアレなので（というか前処理の記事やるんだったらそっちの方に力入れてくれたほうが身になると思う）、次の記事ではその辺を意識してみてください。

2019-07-31 04:45 UTC, Kusumoto-Keisuke approved these changes
お疲れ様です．前回レビューした時より洗練されていて，線形分離可能が何なのかが伝わる記事だと思ったのでApproveします．
”おまけ”のところにコメントしたので，一応確認しておいてください．

2019-07-31 08:02 UTC, TetraMiyazaki approved these changes

2019-08-02 09:29 UTC, forusufia commented
> お疲れ様です！
> コメント入れました～

冒頭を加筆しました。ご確認ください。

2019-08-03 06:16 UTC, senoura approved these changes
記事投降後になってしまいごめんなさい
読みやすくなったと思います
approveします

2019-08-03 06:16 UTC, merged