[Qiita3本目] 機械学習に挑むときに思い出したい線形代数の基礎
furukawa-laboratory/workout_report_2019 pull request #122
Opened 2019-07-16 09:59 UTC by forusufia

## 取り組んだトレーニングの概要
数学基礎の講義の序盤にあった数ベクトルの説明などが長年の線形代数への苦手意識と抜けていたところを埋めてくれました。その内容をなんとか自分なりに説明して記事にします。

HackMD: https://hackmd.io/sDX9xh_IQ6K2OAnmsiE0sQ?view

close #115

印象を和らげるために画像を入れるべきかもしれない...

![3](https://user-images.githubusercontent.com/38308647/61284920-e8265680-a7fa-11e9-8e81-482461251959.PNG)

## 獲得を目指したスキル
- この記事で説明した内容の自身への定着
- 記事を読んだ方が何か気づきを得られる説明

## Action list
- [x] 数字で表現するということ
- [x] 数ベクトルとは
- [x] 線形性とは

## レビュワーへの質問

## 感想
難しい。わかった状態にはまだまだ到達できていないということだろう。具体的なアルゴリズム等を学ぶときも、こういった気持ち・考えかたを心がけるようにする。

2019-07-17 16:01 UTC, ae14watanabe reviewed
コメント、少ないですがHackMDに残しておきました。
要するに、この記事で読者に伝えたいことを明確化してほしいです。
構成の検討とか具体的な添削とかはそこからかなー。
その辺りから悩むようなら他の人に相談してみてください。

2019-07-19 13:06 UTC, forusufia commented
> なんか基礎的な知識と数式のお気持ち的な話と心構え的な話がごっちゃになってる気がする
> 各セクションがポツポツと離れ小島のように書かれているんじゃなくて、うまいこと1つの文脈で通して、1つの読み物として書けないかな？

ご指摘の通りです、ありがとうございます。
ひとつめのセクション「数式にするということ」がメインで、記事のアイディアの出発点としては、言葉をお借りすると”心構え的な話”についての記事にしたいと考えていました。
後ろ二つの話題をあとから追加したために３つ別々のオムニバスになってしまい、ひとつの記事として一貫できていないようです。
後ろ二つの話題は今回は見送って、ひとつめについて膨らませていく方向で修正しようと思います。

2019-07-21 10:22 UTC, ae14watanabe commented
> 後ろ二つの話題
別にそれはそれで記事書いてもいいんじゃないですかね、残したいでしょうせっかくなら

2019-07-22 12:46 UTC, ae14watanabe commented
細かい内容の指摘は「伝えたいこと」「構成」がある程度具体化した上で、Re-request reviewしてくれたらやりますね

2019-07-22 12:47 UTC, yoneda88 reviewed
お疲れ様です！
提案：記事の内容を変えてみてはどうですか？例えばworkoutのスキルセットメニューの一覧からテーマを選んでみては？

もしも変えるならサポートはしますよー

2019-07-22 12:49 UTC, ae14watanabe commented
> 提案：記事の内容を変えてみてはどうですか？例えばworkoutのスキルセットメニューの一覧からテーマを選んでみては？

原田君の他の記事もそうですが、Workoutで習得したいスキルセットと直接関係あるやつはあんまりなさそうだったので、一本ぐらいそれを意識した記事があってもいいかもしれないですね（そんなことないやい！関係してるわ！っていうことなら言ってね）

2019-07-22 12:50 UTC, ae14watanabe commented
別に記事は3本にしなきゃいけないわけでもないしね

2019-07-23 13:28 UTC, takuro-Ishida requested changes
お疲れ様です.
文章全体に関することとしては既出かもしれませんが、まず読者に伝えたいメッセージを具体的にするといいと思いました.

2019-07-25 06:50 UTC, forusufia commented
> > 提案：記事の内容を変えてみてはどうですか？例えばworkoutのスキルセットメニューの一覧からテーマを選んでみては？
> 
> 原田君の他の記事もそうですが、Workoutで習得したいスキルセットと直接関係あるやつはなさそうだったので、一本ぐらいそれを意識した記事があってもいいかもしれないですね（そんなことないやい！関係してるわ！っていうことなら言ってね）

返答が遅くなってしまいましたが、米田さん、渡辺さんのご意見を踏まえ考え中です・・・

１本目はともかく、２本目３本目については直し方や構成にどう手をつけようかといったところなので悩んでいました。
３本目のひとつめの話題については記事にしたいと思っている内容なので、２本目の記事をスキルセット準拠のテーマに変える方向で考えています。

2019-07-25 09:25 UTC, senoura reviewed
お疲れ様です！
コメントしました
これ２本目にして３本目の記事で式の意味？みたいなものの解説がついてたりすると素敵だなあとか思いました

2019-07-25 09:39 UTC, forusufia commented
> お疲れ様です！
> コメントしました
> これ２本目にして３本目の記事で式の意味？みたいなものの解説がついてたりすると素敵だなあとか思いました

確かにそれかっこいい(素敵)です！記事の内容の流れが順番で綺麗になりそうです。
アイディアをありがとうございます。こちらに先に着手して仕上げていこうと思います。

2019-07-26 05:31 UTC, TetraMiyazaki reviewed
まだ制作段階でpendingしてるみたいなので、skipします。
何か困っているなら上級生・同級生に相談してください。研究で誰かと相談するのはうちでは必須のスキルです。
先輩たちが何回も言われてますが「どんなスキルセットを得たいか」というところがあれば、自ずと記事の流れが見えると思います。

2019-07-26 09:07 UTC, takuro-Ishida reviewed
Request change ではなくコメントでした

2019-07-26 09:08 UTC, takuro-Ishida reviewed
石田がコメントしたやつはRequest changeではなく、commentでした

2019-07-26 09:08 UTC, takuro-Ishida reviewed
コメント

2019-07-26 09:08 UTC, takuro-Ishida submitted a review, later dismissed

2019-07-29 10:41 UTC, Kusumoto-Keisuke reviewed
これから修正されると思うので，Commentにしておきます．
公開日が迫ってきているので，方針だけでも共有して欲しいと思います．

2019-07-29 12:19 UTC, kpasso1015 commented
よくわかりませんが、とりあえずコメントはしました。

結局どんなスキルセットを得られることを想定してるんでしょう？
そこだけはっきりしていただけたら、自分はApproveします。

2019-07-30 07:30 UTC, forusufia commented
変更前ですが、３本目の方針について

Workout のスキルセットとほかの方の記事をみながら考え、前処理についてまとめた記事にしようと思います。データの前処理は重要なスキルなので、その獲得/向上を目指します。

2019-08-07 02:59 UTC, ae14watanabe commented
@forusufia 元々書いてたやつも出すだけ出してみたら？

2019-08-07 07:59 UTC, TetraMiyazaki approved these changes
お疲れ様です！
コードも乗ってあってええ感じと思いました。Approveします。
感想コメントをちょっち読んで欲しいのと、渡辺さんが気になっているところを修正しちゃってください。

2019-08-07 08:46 UTC, senoura reviewed
お疲れ様です！
コメントいれました～
コメント全部が修正必須だとは思っていないので自分で必要な範囲は直したと思った時点で伝えてくれたらapproveします

2019-08-07 08:51 UTC, takuro-Ishida reviewed
お疲れ様です.
コメントしました.
細かい説明のところが気になったのでそこを修正していただけたらなと思います.
全体的な流れは良いと思います.

なので、細かいところを修正していただければApproveします.

2019-08-07 09:56 UTC, ae14watanabe requested changes
ご苦労様です！HackMDにコメント寄せておきました。多くは修正してほしい感じなので、よろしく！

2019-08-08 09:43 UTC, yoneda88 requested changes
おつかれさまです！レビュー詳細はhackMDのコメントに書いているので、そっちを見てください！

ちなみに自分はポイントの指摘しかしていないので、
記事としての全体の流れとかの修正をする場合は渡辺君とかののコメントを参考にして下さい！

2019-08-08 11:40 UTC, forusufia commented
校正してくださってありがとうございました！

ひとまず可能な限り修正しましたので、公開しようと思います。

2019-08-10 08:29 UTC, Kusumoto-Keisuke approved these changes
遅くなってしまいすみません．短期間でここまで仕上げてお疲れさまでした．前処理入門の記事として大きな問題はないと思うのでApproveします．

2019-08-16 02:43 UTC, ae14watanabe commented
@forusufia どっか見た方がいいポイントありますかー？

2019-08-19 04:08 UTC, senoura approved these changes
私がしたコメントの修正は確認できたのでapproveします(休んでたので公開後ですが(-_-;))
改めてお疲れさまでした

2019-08-24 11:28 UTC, ae14watanabe approved these changes
まぁもう出したものなのでとりあえずapproveしておきますね。
LabelEncoderとかインターンで使いそうなので大変たすかりまーす
https://qiita.com/forusufia/items/eca1f54a39b1db380589

2019-09-19 23:37 UTC, yoneda88 approved these changes
ごめんなさい。Approve, commit忘れてました

2019-09-19 23:38 UTC, merged