[Qiita2本目] SVMにおけるカーネルトリック
furukawa-laboratory/workout_report_2019 pull request #129
Opened 2019-07-16 15:06 UTC by oirom

取り組んだトレーニングの概要
Qiita記事2本目のプルリクエストです．SVMにおけるカーネルトリックの役割，原理，式の導出，解法について記事にしています．まだ作成途中です．

HackMDリンク https://hackmd.io/@p9rI7JgpQ5iM3kmdfOjSjA/Sk6OdQoWS
close #126 

## 獲得を目指したスキル
- カーネル法の理解
- 正定値カーネルなどの関連用語の理解
- カーネルトリックについての解説スキル

## Action list
未

## 感想
未

2019-07-25 06:39 UTC, yoneda88 commented
これってまだ編集途中？？

2019-07-26 00:52 UTC, ae14watanabe commented
まだ執筆途中のようだったので、レビュワーを一旦全て外しました！不足している点がない（完備な状態）まで持って行ったら改めてレビュワーを立ててもらえると助かるです！

2019-07-27 17:31 UTC, oirom commented
@yoneda88 @ae14watanabe 
記事を完備し，reviewを受けれる状態にしました．
よろしくお願いいたします！

2019-07-28 08:03 UTC, ae14watanabe requested changes
ご苦労様です。大まかな構成は良いと思います。要修正のポイントがいくつかあったのでHackMDにコメントしておきました。確認よろしくです！

2019-07-29 00:38 UTC, oirom commented
@ae14watanabe コメントを頂いた部分を修正いたしました！

数式の部分を特に見ていただきたいですm(_ _)m

追実験を行う人のために乱数値を固定するというのは非常に勉強になりました．
気を付けていこうと思います．

2019-07-29 01:18 UTC, ae14watanabe commented
![image](https://user-images.githubusercontent.com/19607449/62015941-2f90e780-b1ea-11e9-9abc-5b00f69ae9d0.png)
これって、例えばA,B,Cの3クラス分類するときに、AとBの票数が一緒だったときもrejectするんかね？

2019-07-29 01:25 UTC, oirom commented
> @oirom
> ![image](https://user-images.githubusercontent.com/19607449/62015941-2f90e780-b1ea-11e9-9abc-5b00f69ae9d0.png)
> 確認なんですが、これって、例えばA,B,Cの3クラス分類するときに、AとBの票数が一緒でCだけがそれより低いときもrejectするんかね？
> この書き方だとA,B,C全部の投票数が一緒だったときにrejectするんかな？って思ったんだけど

AとBの票数が一緒でCだけ票数が低いときもrejectします．
確かに渡辺さんの言う通り，ABCの票数が全部同じじゃないとrejectしない，ような書き方になってしまってます．

もう少し書き方を考えます．

2019-07-29 01:54 UTC, ae14watanabe commented
@oirom こんなんでどう
![IMG_5691](https://user-images.githubusercontent.com/19607449/62016805-28b8a380-b1ef-11e9-8803-019eff138f67.JPG)

fは他に良い記号があったらそっちの方がいい気がするけど

2019-07-29 03:15 UTC, TetraMiyazaki approved these changes
お疲れ様です! 小言のようなことしかコメントできていませんが確認していただければな、と。
数式については, reject {k_i, ..., k_j}の{k_i, ..., k_j}が要素が複数ある集合っていうのを理解するのに時間かかっちゃいました(間違ってはないです)。 その辺要コミュニケーションと思います。

2019-07-29 04:48 UTC, senoura reviewed
お疲れ様です！
書体については調べたらかなり直すの面倒そうだったのでコメ消ししました。
誤判別の部分のコメントについては、僕自身の理解が足りないため無視でもいいです。
いちおうまだcommentにしておきます。

2019-07-29 07:51 UTC, oirom commented
> お疲れ様です！
> 書体については調べたらかなり直すの面倒そうだったのでコメ消ししました。
> 誤判別の部分のコメントについては、僕自身の理解が足りないため無視でもいいです。
> いちおうまだcommentにしておきます。

コメントありがとうございます！
指摘を受けて，[kNNの弱点，気を付けるべきこと]の章にて，kの選び方による分類誤りについて記述しました．
ご確認よろしくおねがいします．

2019-07-29 10:01 UTC, Kusumoto-Keisuke approved these changes
お疲れ様です．
kNN を知らない私でも，分かり易く読みやすい記事だとおもいました．
少し気になったところにコメントしましたが，すぐ修正できると思うのでApproveします．

2019-07-29 10:38 UTC, yoneda88 approved these changes
OKです。こうしたらもっっとよくなるよ的なコメントはhackmdにしてますので、確認を。
特に必須の修正はなかったので、Approveとします〜

2019-07-29 13:15 UTC, oirom commented
> お疲れ様です．
> kNN を知らない私でも，分かり易く読みやすい記事だとおもいました．
> 少し気になったところにコメントしましたが，すぐ修正できると思うのでApproveします．

コメントありがとうございます．
数式モードの設定ミスや文章を見やすくするための空白など，アドバイスありがとうございます！
修正いたしました！

2019-07-29 13:17 UTC, oirom commented
> お疲れ様です！
> 書体については調べたらかなり直すの面倒そうだったのでコメ消ししました。
> 誤判別の部分のコメントについては、僕自身の理解が足りないため無視でもいいです。
> いちおうまだcommentにしておきます。

コメントありがとうございます！
読者のミスリーディングを減らすため，前半部分に新たに説明を設けました．
[kの選び方]という節です．
reviewよろしくお願いいたしますm(_ _)m

2019-07-31 03:30 UTC, senoura approved these changes
お疲れ様です！
良いと思いますｂ、分かりやすいです
approveします！

2019-08-01 10:18 UTC, ae14watanabe approved these changes
ご苦労様です！HackMDにコメントで数式の表記について指摘してます！そこさえ修正してくれればokです！Approveしますね！

2019-08-02 10:16 UTC, oirom commented
> ご苦労様です！HackMDにコメントで数式の表記について指摘してます！そこさえ修正してくれればokです！Approveしますね！

@ae14watanabe 
ありがとうございます！修正しましたので投稿します！

2019-08-06 13:41 UTC, merged