プレゼンの資料
furukawa-laboratory/workout_report_2019 pull request #141
Opened 2019-08-09 14:22 UTC by tsuno0829

ワークアウトのプレゼン資料をパワーポイントとPDFでアップロードしました

close #138 

## 感想
なんとか発表が終わったので，次はSOMの実装・理解を目指したいと思います．

2019-08-16 02:44 UTC, ae14watanabe requested changes
pdfもぜひ！

2019-08-16 03:25 UTC, tsuno0829 commented
@ae14watanabe 
pdf版も一緒に提出していたのですが，なぜかパワポだけになってました...
もう一度，pdf版を提出しましたので確認よろしくお願いします！

2019-08-16 07:17 UTC, ae14watanabe approved these changes
確認しました！3ヶ月間ご苦労様でしたー！！

2019-09-19 23:39 UTC, takuro-Ishida approved these changes
遅くなりましたがApproveします！

2019-09-19 23:39 UTC, merged