前処理でのつまずきポイント
furukawa-laboratory/workout_report_2019 pull request #45
Opened 2019-04-24 03:26 UTC by hajime9652

https://data-flair.training/blogs/python-ml-data-preprocessing/
のおける↓の部分が解読不可能とのことなので、解釈可能な例を載せました。
![image](https://user-images.githubusercontent.com/8980671/56630348-124cfa00-668c-11e9-8ef3-6963d518d600.png)

2019-04-24 03:28 UTC, TetraMiyazaki approved these changes

2019-04-24 03:40 UTC, ae14watanabe requested changes
@hajime9652 解説コメントをもうちょっと入れてもらえると助かります.
@tsuno0829 に書いてもらってもいいので笑

2019-04-25 00:58 UTC, ae14watanabe commented
昨日挙動を理解しました．解析対象に対して複数のカテゴリカル変数が与えられているような状況の時に，一番安易にヌメリカルな特徴量を作るための関数って感じですかね

2019-04-25 01:03 UTC, hajime9652 commented
https://github.com/furukawa-laboratory/workout_report_2019/pull/45#issuecomment-486480118

そんな感じですね。カテゴリのクラスをまとめてしまってるところが特徴量にしてるって感じありますね。

2019-04-25 01:05 UTC, ae14watanabe approved these changes
お疲れ様でした．
@tsuno0829 くん，これで作った特徴量でRegressionするところまでとかやったらかなり良い記事書けますよ！オヌヌメ！

2019-04-25 01:05 UTC, merged