Create README.md
furukawa-laboratory/workout_report_2019 pull request #75
Opened 2019-05-10 05:58 UTC by takuro-Ishida

trainer用のガイドラインを作成.
レビューする時に意識してほしいことを執筆.

何か勘違いだったりしていることがあるかと思うので,修正お願いします

2019-05-10 06:20 UTC, yoneda88 commented on trainer/README.md
> +本来, レビューのポイントは相手に提示するものだが, 今回はどこを鍛えているのかを確認するために書いてもらうのは良いと思う.
ここの記述って最終的に消すやつ？

2019-05-10 06:21 UTC, yoneda88 commented
> M1がworkout reportで出したpull requestをreviewする時に意識したいことを共有する. また,reviewする際にどこに着目してreviewすればいいのかを明確にする目的もある.

> お互いどのようにレビューしてもらえればいいのかわからない trainerはどの観点でレビューしていいのかわからないし, traineeはレビューしてほしいことに何を書いたらいいのか困っている(と思われる) 本来, レビューのポイントは相手に提示するものだが, 今回はどこを鍛えているのかを確認するために書いてもらうのは良いと思う.

このくだりって最終的に消す予定？？

2019-05-10 07:01 UTC, yoneda88 requested changes
こんな感じで「場合分け」＋「簡単な箇条書き」の方が、あとあと見るときに楽かと。。。
「心得」とか「なんでガイドラインが必要かの理由」とかは、レビューポイントと分けて（別の見出しとかに）書いた方がいいと思います！

2019-05-10 07:01 UTC, yoneda88 commented on trainer/README.md
> +
```suggestion
- 
- 共通のレビューポイント
- 正誤が重要なレビュー場合
  - プログラムの場合
  - ドキュメントの場合
- やったかどうかが重要なレビューの場合
  - プログラムの場合
  - ドキュメントの場合
```

2019-05-10 07:05 UTC, ae14watanabe commented
皆でレビューの時のポイント追加していきますか！
整理は一通り出揃った後で良いので〜

2019-05-11 07:06 UTC, ae14watanabe reviewed
整理しときました．GeneralなReviewポイントがあればみなさん追加していってください．

2019-05-11 07:07 UTC, ae14watanabe commented
> このくだりって最終的に消す予定？？

Issueにある程度書いてあった＋今回のプルリクのお気持ち的な感じだったんで消しときました．

2019-05-13 09:07 UTC, ae14watanabe commented
@yoneda88 @hajime9652 @takuro-Ishida レビューのやり方について追記しました．これでokならapproveくださいまし！！

2019-05-13 09:23 UTC, ae14watanabe commented
#54 も合わせてお願いします！

2019-05-14 04:49 UTC, yoneda88 reviewed
「プログラムの場合」と「理論の場合」の場合分けが見やすくなるように修正しました

2019-05-14 04:49 UTC, yoneda88 commented on trainer/README.md
> +   - プログラミングの場合はさらっと目を通し，明らかに手抜きでないか確認する
```suggestion
   - <u>プログラミングの場合</u>
      - さらっと目を通し，明らかに手抜きでないか確認する
```

2019-05-14 04:49 UTC, yoneda88 commented on trainer/README.md
> +   - 理論の場合は，以下を確認
```suggestion
   - <u>理論の場合</u>
```

2019-05-14 05:00 UTC, ae14watanabe approved these changes
構成を修正しておきました。

2019-05-14 05:01 UTC, ae14watanabe commented
@takuro-Ishida 石田氏はもともとこのプルリクの作成主だからreviewはできないけど、俺とか米田さんの修正内容は問題なさそうかね？

2019-05-14 09:41 UTC, yoneda88 approved these changes
自分はこれでOKだと思います!

2019-05-15 01:08 UTC, hajime9652 approved these changes

2019-05-15 01:09 UTC, merged